---
title: "Individualisation report"
output: html_document
#   pdf_document:
#     latex_engine: xelatex
# header-includes:
#    - \usepackage{fontspec}
#    - \setmainfont{Lato}
params:
  df: NA
  trace: NA
  db: NA
  unk: NA
  method: NA
  Th: NA
  allele_freq: NA
  known_alleles: NA
---

Generated on **`r format(Sys.time(), '%d %B %Y, %X %Z')`**  

------

```{r, echo=FALSE, message = FALSE, warning = F}

#~~ Prepare reference database

if(params$allele_freq == T){
  
  # Genalex:
  
  db <- params$df[[2]] %>%
    .[-c(1:10,12),-1]
  loci <- c("size", db[1,c(2:ncol(db))])
  
  db <- db %>%
    .[-1,] %>%
    `colnames<-`(unlist(loci)) %>%
    gather(locus, freq, -size) %>%
    drop_na() %>%
    mutate(freq = as.numeric(freq),
           size = as.numeric(size))
  
} 

if(params$allele_freq == F){
  
  # Read in genotypes and calculate allele freqs
  
  db <- params$df %>%
    select(-ID) %>%
    gather(locus, size) %>%
    separate(locus, c("locus", "dip")) %>%
    group_by(locus, size) %>%
    dplyr::summarise(n = n()) %>%
    group_by(locus) %>%
    mutate(freq = n/sum(n))
  
}
```


```{r, echo=FALSE, message = FALSE, warning = F}

#~~ Prepare trace profile

# If unknown individual's alleles are known, read in unknown
# Extract allele freqs from db

if(params$known_alleles == TRUE){
  
  un <- params$trace %>%
    gather(locus, size, -ID) %>%
    mutate(size = as.numeric(size)) %>%
    separate(locus, c("locus", "dip")) %>%
    mutate(dip = rep(c("p", "q"), nrow(.)/2)) %>%
    left_join(db, by = c("locus", "size")) %>%
    select(locus, dip, freq) %>%
    spread(dip, freq) %>%
    select(locus, p, q)
  
  #~~~~~~~~~~~~~~~~~~~#
  #        RMP        #
  #~~~~~~~~~~~~~~~~~~~#
  
  # Rob's method (same result at Pmatch(mat))
  
  Th <- params$Th
  
  rmp <- un %>%
    mutate(p_het = (2*(Th+((1-Th)*p))*(Th+((1-Th)*q)))/((1+Th)*(1+(2*Th))),
           p_hom = (((2*Th)+((1-Th)*p))*((3*Th)+((1-Th)*p)))/((1+Th)*(1+(2*Th))),
           prob = case_when(p == q ~ p_hom,
                            TRUE ~ p_het))
  
  cuml_prob <- prod(rmp$prob, na.rm = T)
  
  # Take the reciprocal for the cumulative likelihood
  cuml_likelihood <- 1/cuml_prob
  
}

# If unknown individual's alleles are not known, take two most common as conservative approach

if(params$known_alleles == F){
  
  top_2 <- db %>%
    group_by(locus) %>%
    top_n(2, freq) %>%
    arrange(locus, desc(freq)) %>%
    mutate(allele = rep(c("p", "q"))) %>%
    select(locus, allele, freq) %>%
    spread(allele, freq)
  
  #~~~~~~~~~~~~~~~~~~~#
  #        RMP        #
  #~~~~~~~~~~~~~~~~~~~#
  
  rmp <- top_2 %>%
    mutate(p_het = (2*(Th+((1-Th)*p))*(Th+((1-Th)*q)))/((1+Th)*(1+(2*Th))),
           p_hom = (((2*Th)+((1-Th)*p))*((3*Th)+((1-Th)*p)))/((1+Th)*(1+(2*Th))),
           prob = case_when(p == q ~ p_hom,
                            TRUE ~ p_het))
  cuml_prob <- prod(rmp$prob, na.rm = T)
  
  # Take the reciprocal for the cumulative likelihood
  cuml_likelihood <- 1/cuml_prob

}


# Number of markers analysed: NAs included? For non known alleles, NAs not taken into account

```

Individualization test statistic used: **`r params$method`**  
Trace profile: **`r params$unk`**  
Reference database used: **`r params$db`**  
Number of markers analysed: **`r length(unique(db$locus))`**  
Marker type: **Microsatellites**  
Known alleles = **`r params$known_alleles`**  
Theta = **`r params$Th`**  

------

#### Result

```{r, echo=FALSE, message = FALSE, warning = F}

# Prepare statements

if(params$method == "Random match probability"){
  
  str0 <- paste0("Match: Random match probability is ", "<b>",
                 cuml_prob,"</b>")
  str1 <- paste0("The probability of a match if this genotype 
                           derived from an individual other than the suspect is ", "<b>",
                 cuml_prob,"</b>")
  
  HTML(paste(str0, str1, sep = '<br/>'))
}
```

```{r, echo=FALSE, message = FALSE, warning = F}

if(params$method == "Likelihood ratio approach"){
  
  str0 <- paste0("Match: Cumulative likelihood is ", "<b>",
                 cuml_likelihood,"</b>")
  str1 <- paste0("It is ", "<b>",cuml_likelihood,"</b>", 
                 " times more likely to obtain this DNA profile if it originated from the suspect than 
                 from an unknown unrelated individual in the population.")

  HTML(paste(str0, str1, sep = '<br/>'))

}


```


------

#### R version and platform
```{r}
sessionInfo()
```
